/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvertisementCreateForm: typeof import('./src/components/forms/AdvertisementCreateForm.vue')['default']
    AdvertisementItem: typeof import('./src/components/pages/AdvertisementItem.vue')['default']
    AdvertisementUpdateForm: typeof import('./src/components/forms/AdvertisementUpdateForm.vue')['default']
    ArticleCreateForm: typeof import('./src/components/forms/ArticleCreateForm.vue')['default']
    ArticleList: typeof import('./src/components/pages/ArticleList.vue')['default']
    ArticleUpdateForm: typeof import('./src/components/forms/ArticleUpdateForm.vue')['default']
    AuthPopover: typeof import('./src/components/common/AuthPopover.vue')['default']
    BreadcrumbItem: typeof import('./src/components/layput/BreadcrumbItem.vue')['default']
    CalendarItem: typeof import('./src/components/pages/CalendarItem.vue')['default']
    CommentItem: typeof import('./src/components/common/CommentItem.vue')['default']
    DashboardTag: typeof import('./src/components/layput/DashboardTag.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    FeedbackItem: typeof import('./src/components/pages/FeedbackItem.vue')['default']
    FeedbackReplyForm: typeof import('./src/components/forms/FeedbackReplyForm.vue')['default']
    ForgotPasswordForm: typeof import('./src/components/forms/ForgotPasswordForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginForm: typeof import('./src/components/forms/LoginForm.vue')['default']
    Logo: typeof import('./src/components/widgets/logo.vue')['default']
    LogoView: typeof import('./src/components/widgets/LogoView.vue')['default']
    MenuItem: typeof import('./src/components/layput/Dashboard/MenuItem.vue')['default']
    NewsItem: typeof import('./src/components/pages/NewsItem.vue')['default']
    ProfileCard: typeof import('./src/components/pages/ProfileCard.vue')['default']
    RecentComments: typeof import('./src/components/pages/RecentComments.vue')['default']
    RegisterForm: typeof import('./src/components/forms/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagCloud: typeof import('./src/components/pages/TagCloud.vue')['default']
    UserCard: typeof import('./src/components/widgets/UserCard.vue')['default']
    UserCardPopover: typeof import('./src/components/common/UserCardPopover.vue')['default']
    UserChart: typeof import('./src/components/widgets/UserActivity/UserChart.vue')['default']
    WebFooter: typeof import('./src/components/layput/WebFooter.vue')['default']
    WebNavbar: typeof import('./src/components/layput/WebNavbar.vue')['default']
  }
}
