/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthPopover: typeof import('./src/components/common/AuthPopover.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ForgotPasswordForm: typeof import('./src/components/forms/ForgotPasswordForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginForm: typeof import('./src/components/forms/LoginForm.vue')['default']
    Logo: typeof import('./src/components/widgets/logo.vue')['default']
    LogoView: typeof import('./src/components/widgets/LogoView.vue')['default']
    RegisterForm: typeof import('./src/components/forms/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WebNavbar: typeof import('./src/components/layput/WebNavbar.vue')['default']
  }
}
